/**
 * Career Test V2 — office-administration pilot career profiles (V2.4D pilot).
 *
 * Pilot subset only. Not the full 60-career catalog.
 * Do not rename to CAREERS_V2 until the full catalog is authorized.
 */

import type { DimensionLevelV2 } from "./dimensions";
import type { CareerProfileV2 } from "./profiles";

/** Local brand helper — not exported. */
function lvl(value: 0 | 2500 | 5000 | 7500 | 10000): DimensionLevelV2 {
  return value as DimensionLevelV2;
}

/**
 * Exact six office-administration pilot records in canonical CAREER_IDS_V2 order
 * for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const OFFICE_ADMINISTRATION_PILOT_CAREERS_V2 = [
  {
    id: "v2-administrative-assistant",
    titleEn: "Administrative Assistant",
    titleZh: "行政助理",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(2500),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(7500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh:
      "提供办公室日常支持，包括日程安排、文档处理和一般事务协调。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "与设施协调员不同：偏综合行政，而非设施工单或供应商协调。",
    similarityGroupId: "sim-admin-vs-facilities-coord",
  },
  {
    id: "v2-bookkeeper",
    titleEn: "Bookkeeper",
    titleZh: "簿记员",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(2500),
        routineVariety: lvl(2500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(0),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "负责日常簿记与对账等财务记录工作。",
    verification: { status: "editorial-only" },
  },
  {
    id: "v2-project-coordinator",
    titleEn: "Project Coordinator",
    titleZh: "项目协调员",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(5000),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(10000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "协调项目日程、相关方沟通与项目文档。",
    verification: { status: "editorial-only" },
  },
  {
    id: "v2-estimator",
    titleEn: "Construction Estimator",
    titleZh: "工程造价估算员",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(7500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(0),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "根据图纸与报价资料估算工程造价。",
    verification: { status: "editorial-only" },
  },
  {
    id: "v2-receptionist",
    titleEn: "Receptionist",
    titleZh: "前台接待",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "接待来访人员，处理前台来电与到访事务。",
    verification: { status: "editorial-only" },
  },
  {
    id: "v2-payroll-clerk",
    titleEn: "Payroll Clerk",
    titleZh: "薪资文员",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(0),
        routineVariety: lvl(0),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(0),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(0),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "在办公财务流程中处理薪资相关录入与流程事务。",
    verification: { status: "editorial-only" },
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact seven building-operations-facilities pilot records in canonical
 * CAREER_IDS_V2 order for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const BUILDING_OPERATIONS_FACILITIES_PILOT_CAREERS_V2 = [
  {
    id: "v2-building-operator",
    titleEn: "Building Operator",
    titleZh: "楼宇运行员",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(2500),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(7500),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh:
      "巡检并运行楼宇机电与相关设备系统（含例行巡查与报警处理）。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏楼宇系统运行与巡检，不同于单元物业现场维修；也不同于医院机构环境下的设施技师。",
    similarityGroupId: "sim-building-systems-maintenance",
  },
  {
    id: "v2-hospital-facilities-technician",
    titleEn: "Hospital Facilities Technician",
    titleZh: "医院设施技师",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "common-or-required",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(7500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(2500),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(7500),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(7500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh:
      "在医院等全天候机构环境中维护机房与设施基础设施（非临床照护）。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "医院机构环境下的设施维护，不同于一般商业楼宇运行员；不是临床护理岗位。",
    similarityGroupId: "sim-building-systems-maintenance",
  },
  {
    id: "v2-property-maintenance-worker",
    titleEn: "Property Maintenance Worker",
    titleZh: "物业维修工",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "frequent-high",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(10000),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(7500),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "对住宅或商业物业进行单元与现场的动手维修。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏单元与物业现场维修，不同于楼宇机电系统运行巡检。",
    similarityGroupId: "sim-building-systems-maintenance",
  },
  {
    id: "v2-commercial-custodian",
    titleEn: "Commercial Custodian",
    titleZh: "商业清洁与后勤员",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(2500),
        routineVariety: lvl(2500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在商业楼宇提供清洁与轻度设施后勤维护。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "商业楼宇清洁后勤场景，不同于学校董事会环境下的学校清洁与设施维护。",
    similarityGroupId: "sim-custodial-context",
  },
  {
    id: "v2-groundskeeper",
    titleEn: "Groundskeeper",
    titleZh: "场地绿化维护员",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "frequent-high",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(10000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(7500),
      indoorOutdoorPreference: lvl(10000),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(2500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "维护室外场地、绿化与季节性户外场地保养。",
    verification: { status: "editorial-only" },
  },
  {
    id: "v2-maintenance-helper",
    titleEn: "Maintenance Helper",
    titleZh: "维修帮工",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(2500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(2500),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "以入门帮工方式协助运行员与技工完成基础设施任务。",
    verification: { status: "editorial-only" },
    mismatchNotesZh: "入门帮工角色，责任与独立性低于楼宇运行员。",
  },
  {
    id: "v2-facilities-coordinator",
    titleEn: "Facilities Coordinator",
    titleZh: "设施协调员",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(2500),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(5000),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(10000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh:
      "协调设施工单、供应商与设施后勤安排，动手操作负荷较低。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏设施工单与供应商协调，不同于综合行政助理的一般办公室事务。",
    similarityGroupId: "sim-admin-vs-facilities-coord",
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact three public-sector-institutional pilot records in canonical
 * CAREER_IDS_V2 order for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const PUBLIC_SECTOR_INSTITUTIONAL_PILOT_CAREERS_V2 = [
  {
    id: "v2-municipal-maintenance-worker",
    titleEn: "Municipal Maintenance Worker",
    titleZh: "市政设施维护员",
    primaryFamily: "public-sector-institutional",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "frequent-high",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(10000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(7500),
      indoorOutdoorPreference: lvl(5000),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在公共部门场景下维护市政或公共设施。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏公共部门市政设施维护场景，不同于商业或住宅物业的单元现场维修。",
  },
  {
    id: "v2-school-custodian",
    titleEn: "School Custodian",
    titleZh: "学校清洁与设施维护",
    primaryFamily: "public-sector-institutional",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(2500),
        routineVariety: lvl(2500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在学校场景提供清洁与轻度设施维护支持。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "学校董事会环境下的学校清洁与设施维护，不同于商业楼宇清洁后勤场景。",
    similarityGroupId: "sim-custodial-context",
  },
  {
    id: "v2-security-guard",
    titleEn: "Security Guard",
    titleZh: "保安",
    primaryFamily: "public-sector-institutional",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "common-or-required",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(5000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(7500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "负责场地出入管控、巡查与安保值守（常含轮班）。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏现场安保与出入管控，不同于设施维修或清洁维护岗位。",
  },
] as const satisfies readonly CareerProfileV2[];
