/**
 * Career Test V2 — office-administration pilot career profiles (V2.4D pilot).
 *
 * Pilot subset only. Not the full 60-career catalog.
 * Do not rename to CAREERS_V2 until the full catalog is authorized.
 */

import type { DimensionLevelV2 } from "./dimensions";
import type { CareerProfileV2 } from "./profiles";

/** Local brand helper — not exported. */
function lvl(value: 0 | 2500 | 5000 | 7500 | 10000): DimensionLevelV2 {
  return value as DimensionLevelV2;
}

/**
 * Exact six office-administration pilot records in canonical CAREER_IDS_V2 order
 * for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const OFFICE_ADMINISTRATION_PILOT_CAREERS_V2 = [
  {
    id: "v2-administrative-assistant",
    titleEn: "Administrative Assistant",
    titleZh: "行政助理",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(2500),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(7500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh:
      "提供办公室日常支持，包括日程安排、文档处理和一般事务协调。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "与设施协调员不同：偏综合行政，而非设施工单或供应商协调。",
    similarityGroupId: "sim-admin-vs-facilities-coord",
  },
  {
    id: "v2-bookkeeper",
    titleEn: "Bookkeeper",
    titleZh: "簿记员",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(2500),
        routineVariety: lvl(2500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(0),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "负责日常簿记与对账等财务记录工作。",
    verification: { status: "editorial-only" },
  },
  {
    id: "v2-project-coordinator",
    titleEn: "Project Coordinator",
    titleZh: "项目协调员",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(5000),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(10000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "协调项目日程、相关方沟通与项目文档。",
    verification: { status: "editorial-only" },
  },
  {
    id: "v2-estimator",
    titleEn: "Construction Estimator",
    titleZh: "工程造价估算员",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(7500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(0),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "根据图纸与报价资料估算工程造价。",
    verification: { status: "editorial-only" },
  },
  {
    id: "v2-receptionist",
    titleEn: "Receptionist",
    titleZh: "前台接待",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "接待来访人员，处理前台来电与到访事务。",
    verification: { status: "editorial-only" },
  },
  {
    id: "v2-payroll-clerk",
    titleEn: "Payroll Clerk",
    titleZh: "薪资文员",
    primaryFamily: "office-administration",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(0),
        routineVariety: lvl(0),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(0),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(0),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "在办公财务流程中处理薪资相关录入与流程事务。",
    verification: { status: "editorial-only" },
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact seven building-operations-facilities pilot records in canonical
 * CAREER_IDS_V2 order for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const BUILDING_OPERATIONS_FACILITIES_PILOT_CAREERS_V2 = [
  {
    id: "v2-building-operator",
    titleEn: "Building Operator",
    titleZh: "楼宇运行员",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(2500),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(7500),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh:
      "巡检并运行楼宇机电与相关设备系统（含例行巡查与报警处理）。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏楼宇系统运行与巡检，不同于单元物业现场维修；也不同于医院机构环境下的设施技师。",
    similarityGroupId: "sim-building-systems-maintenance",
  },
  {
    id: "v2-hospital-facilities-technician",
    titleEn: "Hospital Facilities Technician",
    titleZh: "医院设施技师",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "common-or-required",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(7500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(2500),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(7500),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(7500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh:
      "在医院等全天候机构环境中维护机房与设施基础设施（非临床照护）。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "医院机构环境下的设施维护，不同于一般商业楼宇运行员；不是临床护理岗位。",
    similarityGroupId: "sim-building-systems-maintenance",
  },
  {
    id: "v2-property-maintenance-worker",
    titleEn: "Property Maintenance Worker",
    titleZh: "物业维修工",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "frequent-high",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(10000),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(7500),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "对住宅或商业物业进行单元与现场的动手维修。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏单元与物业现场维修，不同于楼宇机电系统运行巡检。",
    similarityGroupId: "sim-building-systems-maintenance",
  },
  {
    id: "v2-commercial-custodian",
    titleEn: "Commercial Custodian",
    titleZh: "商业清洁与后勤员",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(2500),
        routineVariety: lvl(2500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在商业楼宇提供清洁与轻度设施后勤维护。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "商业楼宇清洁后勤场景，不同于学校董事会环境下的学校清洁与设施维护。",
    similarityGroupId: "sim-custodial-context",
  },
  {
    id: "v2-groundskeeper",
    titleEn: "Groundskeeper",
    titleZh: "场地绿化维护员",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "frequent-high",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(10000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(7500),
      indoorOutdoorPreference: lvl(10000),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(2500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "维护室外场地、绿化与季节性户外场地保养。",
    verification: { status: "editorial-only" },
  },
  {
    id: "v2-maintenance-helper",
    titleEn: "Maintenance Helper",
    titleZh: "维修帮工",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(2500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(2500),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "以入门帮工方式协助运行员与技工完成基础设施任务。",
    verification: { status: "editorial-only" },
    mismatchNotesZh: "入门帮工角色，责任与独立性低于楼宇运行员。",
  },
  {
    id: "v2-facilities-coordinator",
    titleEn: "Facilities Coordinator",
    titleZh: "设施协调员",
    primaryFamily: "building-operations-facilities",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(2500),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(5000),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(10000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh:
      "协调设施工单、供应商与设施后勤安排，动手操作负荷较低。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏设施工单与供应商协调，不同于综合行政助理的一般办公室事务。",
    similarityGroupId: "sim-admin-vs-facilities-coord",
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact three public-sector-institutional pilot records in canonical
 * CAREER_IDS_V2 order for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const PUBLIC_SECTOR_INSTITUTIONAL_PILOT_CAREERS_V2 = [
  {
    id: "v2-municipal-maintenance-worker",
    titleEn: "Municipal Maintenance Worker",
    titleZh: "市政设施维护员",
    primaryFamily: "public-sector-institutional",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "frequent-high",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(10000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(7500),
      indoorOutdoorPreference: lvl(5000),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在公共部门场景下维护市政或公共设施。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏公共部门市政设施维护场景，不同于商业或住宅物业的单元现场维修。",
  },
  {
    id: "v2-school-custodian",
    titleEn: "School Custodian",
    titleZh: "学校清洁与设施维护",
    primaryFamily: "public-sector-institutional",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(2500),
        routineVariety: lvl(2500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在学校场景提供清洁与轻度设施维护支持。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "学校董事会环境下的学校清洁与设施维护，不同于商业楼宇清洁后勤场景。",
    similarityGroupId: "sim-custodial-context",
  },
  {
    id: "v2-security-guard",
    titleEn: "Security Guard",
    titleZh: "保安",
    primaryFamily: "public-sector-institutional",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "common-or-required",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(5000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(7500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "负责场地出入管控、巡查与安保值守（常含轮班）。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏现场安保与出入管控，不同于设施维修或清洁维护岗位。",
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact four manufacturing-production pilot records in canonical
 * CAREER_IDS_V2 order for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const MANUFACTURING_PRODUCTION_PILOT_CAREERS_V2 = [
  {
    id: "v2-assembler",
    titleEn: "Assembler",
    titleZh: "装配工",
    primaryFamily: "manufacturing-production",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(2500),
        handsOnDesk: lvl(10000),
        structureJudgment: lvl(0),
        routineVariety: lvl(0),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(0),
      englishReadiness: lvl(2500),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(0),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在生产线上装配产品或零部件。",
    verification: { status: "editorial-only" },
    mismatchNotesZh: "偏产线手工装配作业，不同于生产机器操作岗位。",
  },
  {
    id: "v2-machine-operator",
    titleEn: "Machine Operator",
    titleZh: "机器操作员",
    primaryFamily: "manufacturing-production",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(2500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(0),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "按车间规程操作生产机器。",
    verification: { status: "editorial-only" },
    mismatchNotesZh: "偏生产机器操作，不同于产线手工装配岗位。",
  },
  {
    id: "v2-quality-control-inspector",
    titleEn: "Quality Control Inspector",
    titleZh: "质检员",
    primaryFamily: "manufacturing-production",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(5000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(0),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "检查产品或工序质量并记录结果。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏质量检查与结果记录，不同于产线装配或机器操作执行岗。",
  },
  {
    id: "v2-production-supervisor",
    titleEn: "Production Supervisor",
    titleZh: "生产主管",
    primaryFamily: "manufacturing-production",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(2500),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(7500),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(10000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "督导制造产线人员与产出安排。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏产线人员与产出督导，不同于一线装配、机器操作或质检执行岗。",
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact four hospitality-food-services pilot records in canonical
 * CAREER_IDS_V2 order for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const HOSPITALITY_FOOD_SERVICES_PILOT_CAREERS_V2 = [
  {
    id: "v2-commercial-cook",
    titleEn: "Cook",
    titleZh: "商业厨师",
    primaryFamily: "hospitality-food-services",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(10000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(0),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(7500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "在商业厨房制作菜品与餐食。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏商业厨房烹饪制作，不同于厨房帮工支持或餐饮督导管理。",
    similarityGroupId: "sim-kitchen-leadership",
  },
  {
    id: "v2-kitchen-helper",
    titleEn: "Kitchen Helper",
    titleZh: "厨房帮工",
    primaryFamily: "hospitality-food-services",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(2500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(0),
        routineVariety: lvl(2500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(0),
      englishReadiness: lvl(2500),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在商业厨房提供入门备料与厨房支持。",
    verification: { status: "editorial-only" },
    mismatchNotesZh: "偏入门厨房支持，责任与烹饪深度低于商业厨师。",
  },
  {
    id: "v2-food-service-supervisor",
    titleEn: "Food Service Supervisor",
    titleZh: "餐饮主管",
    primaryFamily: "hospitality-food-services",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(2500),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(7500),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(7500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(10000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "督导餐饮服务人员、班次与服务标准。",
    verification: { status: "editorial-only" },
    mismatchNotesZh: "偏餐饮人员与班次督导，不同于一线烹饪制作。",
    similarityGroupId: "sim-kitchen-leadership",
  },
  {
    id: "v2-hotel-front-desk-agent",
    titleEn: "Hotel Front Desk Agent",
    titleZh: "酒店前台",
    primaryFamily: "hospitality-food-services",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(7500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "办理酒店宾客入住/退房并提供前台接待服务。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏酒店前台宾客接待，不同于厨房烹饪或餐饮督导岗位。",
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact six transportation-logistics pilot records in canonical
 * CAREER_IDS_V2 order for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const TRANSPORTATION_LOGISTICS_PILOT_CAREERS_V2 = [
  {
    id: "v2-truck-driver",
    titleEn: "Truck Driver",
    titleZh: "卡车司机",
    primaryFamily: "transportation-logistics",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(10000),
        handsOnDesk: lvl(5000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(5000),
      customerFacingTolerance: lvl(0),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(7500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "在公路或长途货运线路上驾驶货运车辆。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏公路货运长途驾驶，不同于本地配送或客运公交。",
  },
  {
    id: "v2-local-delivery-driver",
    titleEn: "Local Delivery Driver",
    titleZh: "本地配送司机",
    primaryFamily: "transportation-logistics",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(5000),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(7500),
      indoorOutdoorPreference: lvl(5000),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "完成本地或城市范围内的货物或包裹配送。",
    verification: { status: "editorial-only" },
    mismatchNotesZh: "偏本地城市配送，不同于公路货运长途驾驶。",
  },
  {
    id: "v2-warehouse-associate",
    titleEn: "Warehouse Associate",
    titleZh: "仓库理货员",
    primaryFamily: "transportation-logistics",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "frequent-high",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(2500),
        handsOnDesk: lvl(10000),
        structureJudgment: lvl(0),
        routineVariety: lvl(2500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(7500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(0),
      englishReadiness: lvl(2500),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在仓库一线完成拣货、包装与收货等理货作业。",
    verification: { status: "editorial-only" },
    mismatchNotesZh: "偏仓库一线理货作业，不同于仓库主管督导。",
    similarityGroupId: "sim-warehouse-ladder",
  },
  {
    id: "v2-forklift-operator",
    titleEn: "Forklift Operator",
    titleZh: "叉车操作员",
    primaryFamily: "transportation-logistics",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(10000),
        structureJudgment: lvl(2500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(0),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "使用叉车或类似仓储设备搬运物料。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏叉车等仓储设备操作，不同于一般仓库理货员。",
  },
  {
    id: "v2-warehouse-supervisor",
    titleEn: "Warehouse Supervisor",
    titleZh: "仓库主管",
    primaryFamily: "transportation-logistics",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(2500),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(7500),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(7500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(10000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "督导仓库人员协调、班次与现场作业优先级。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏仓库班次与人员督导，不同于一线理货或叉车操作。",
    similarityGroupId: "sim-warehouse-ladder",
  },
  {
    id: "v2-transit-operator",
    titleEn: "Transit Bus Operator",
    titleZh: "公交车驾驶员",
    primaryFamily: "transportation-logistics",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "common-or-required",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(5000),
        structureJudgment: lvl(2500),
        routineVariety: lvl(2500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(7500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(7500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "在固定线路上驾驶客运公交车。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏固定线路客运公交驾驶，不同于货运卡车或本地货物配送。",
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact five technology pilot records in canonical CAREER_IDS_V2 order
 * for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const TECHNOLOGY_PILOT_CAREERS_V2 = [
  {
    id: "v2-software-developer",
    titleEn: "Software Developer",
    titleZh: "软件开发工程师",
    primaryFamily: "technology",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "设计并构建软件应用。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏软件应用开发构建，不同于面向用户的IT技术支持。",
    similarityGroupId: "sim-software-vs-support",
  },
  {
    id: "v2-data-analyst",
    titleEn: "Data Analyst",
    titleZh: "数据分析师",
    primaryFamily: "technology",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(0),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "使用表格、SQL或BI类工具分析业务数据。",
    verification: { status: "editorial-only" },
    mismatchNotesZh: "偏业务数据分析，不同于软件应用开发。",
  },
  {
    id: "v2-it-support-specialist",
    titleEn: "IT Support Specialist",
    titleZh: "IT 技术支持专员",
    primaryFamily: "technology",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(5000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(7500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "排查终端用户设备与职场应用问题。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏终端用户设备与应用支持，不同于软件开发。",
    similarityGroupId: "sim-software-vs-support",
  },
  {
    id: "v2-network-technician",
    titleEn: "Computer Network Technician",
    titleZh: "计算机网络技师",
    primaryFamily: "technology",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "安装并维护网络连通及相关设备。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏网络连通与相关设备维护，不同于一般终端IT支持。",
  },
  {
    id: "v2-graphic-designer",
    titleEn: "Graphic Designer",
    titleZh: "平面设计师",
    primaryFamily: "technology",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(0),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "为品牌与媒体创作视觉设计素材。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏品牌与媒体视觉设计，不同于软件开发或IT支持运维。",
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact four sales-customer-service pilot records in canonical
 * CAREER_IDS_V2 order for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const SALES_CUSTOMER_SERVICE_PILOT_CAREERS_V2 = [
  {
    id: "v2-customer-service-representative",
    titleEn: "Customer Service Representative",
    titleZh: "客服代表",
    primaryFamily: "sales-customer-service",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "通过电话、聊天或邮件处理客户问询。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏电话、聊天或邮件客户问询处理，不同于卖场零售销售或结果导向的内部销售。",
  },
  {
    id: "v2-retail-sales-associate",
    titleEn: "Retail Sales Associate",
    titleZh: "零售销售员",
    primaryFamily: "sales-customer-service",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(2500),
        structureJudgment: lvl(5000),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在零售卖场销售商品并协助顾客。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏零售卖场销售与顾客协助，不同于电话客服或房产销售。",
  },
  {
    id: "v2-inside-sales-representative",
    titleEn: "Inside Sales Representative",
    titleZh: "内部销售代表",
    primaryFamily: "sales-customer-service",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(7500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在办公室或远程销售渠道推进销售结果。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏办公室或远程渠道推进销售结果，不同于服务型客户问询处理。",
  },
  {
    id: "v2-real-estate-salesperson",
    titleEn: "Real Estate Salesperson",
    titleZh: "房地产销售人员",
    primaryFamily: "sales-customer-service",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(2500),
        structureJudgment: lvl(7500),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(7500),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(7500),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "协助客户买卖或租赁房产。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏协助客户买卖或租赁房产，不同于卖场零售销售。",
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact four education-community-services pilot records in canonical
 * CAREER_IDS_V2 order for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const EDUCATION_COMMUNITY_SERVICES_PILOT_CAREERS_V2 = [
  {
    id: "v2-early-childhood-educator",
    titleEn: "Early Childhood Educator",
    titleZh: "幼教老师",
    primaryFamily: "education-community-services",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(2500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(7500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(7500),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(2500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "在儿童照护环境中教育并照护幼儿。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏托幼照护环境中的幼儿教育与照护，不同于中小学教育助理。",
  },
  {
    id: "v2-educational-assistant",
    titleEn: "Educational Assistant",
    titleZh: "教育助理",
    primaryFamily: "education-community-services",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(2500),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "在中小学环境中协助教师与学生。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏中小学环境中协助教师与学生，不同于托幼幼儿教育。",
  },
  {
    id: "v2-community-support-worker",
    titleEn: "Community Support Worker",
    titleZh: "社区支持工作者",
    primaryFamily: "education-community-services",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(7500),
        handsOnDesk: lvl(5000),
        structureJudgment: lvl(5000),
        routineVariety: lvl(7500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(2500),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(7500),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "支持社区成员的日常生活与社区参与目标。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏社区成员日常生活与社区参与支持，不同于新移民安置导向与转介。",
    similarityGroupId: "sim-community-settlement",
  },
  {
    id: "v2-settlement-worker",
    titleEn: "Settlement Worker",
    titleZh: "新移民安置工作者",
    primaryFamily: "education-community-services",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(7500),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "帮助新移民获取安置导向、转介及相关服务。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏新移民安置导向、转介及相关服务，不同于一般社区生活支持。",
    similarityGroupId: "sim-community-settlement",
  },
] as const satisfies readonly CareerProfileV2[];

/**
 * Exact six healthcare-support pilot records in canonical CAREER_IDS_V2
 * order for this family. Incomplete catalog — do not treat as CAREERS_V2.
 */
export const HEALTHCARE_SUPPORT_PILOT_CAREERS_V2 = [
  {
    id: "v2-psw",
    titleEn: "Personal Support Worker",
    titleZh: "个人支持工作者",
    primaryFamily: "healthcare-support",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "common-or-required",
      heavyPhysicalExposure: "frequent-high",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(7500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(7500),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "在居家或机构环境中提供个人照护与日常生活支持。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏个人照护与日常生活支持，不同于诊所行政或实验室支持。",
  },
  {
    id: "v2-medical-office-assistant",
    titleEn: "Medical Office Assistant",
    titleZh: "医疗行政助理",
    primaryFamily: "healthcare-support",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(0),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(0),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(7500),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "处理诊所行政、预约安排与前台患者流程。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏诊所前台行政与患者流程，不同于实验室标本与化验支持。",
    similarityGroupId: "sim-clinic-admin-vs-lab",
  },
  {
    id: "v2-pharmacy-assistant",
    titleEn: "Pharmacy Assistant",
    titleZh: "药房助理",
    primaryFamily: "healthcare-support",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(2500),
        handsOnDesk: lvl(2500),
        structureJudgment: lvl(2500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(2500),
      formalEntryWillingness: lvl(2500),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "在药房团队指导下支持柜台与配药相关流程。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏药房柜台与配药流程支持，不同于牙科椅旁协助或诊所行政。",
  },
  {
    id: "v2-dental-assistant",
    titleEn: "Dental Assistant",
    titleZh: "牙科助理",
    primaryFamily: "healthcare-support",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "not-typical",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(2500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(5000),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(10000),
      englishReadiness: lvl(7500),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(0),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "协助椅旁牙科操作及诊所灭菌相关流程。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏椅旁牙科协助与灭菌流程，不同于医疗诊所行政。",
  },
  {
    id: "v2-dietary-aide",
    titleEn: "Dietary Aide",
    titleZh: "膳食助理",
    primaryFamily: "healthcare-support",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "moderate",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(2500),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(2500),
        routineVariety: lvl(2500),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(5000),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(5000),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(0),
      formalEntryWillingness: lvl(0),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(5000),
      careerEntryPracticality: "learn-on-job",
    },
    descriptionZh: "在医院或长期照护餐饮作业中支持患者/住户膳食服务。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏机构膳食服务支持，不同于餐馆烹饪岗位。",
  },
  {
    id: "v2-medical-laboratory-assistant",
    titleEn: "Medical Laboratory Assistant",
    titleZh: "医疗实验室助理",
    primaryFamily: "healthcare-support",
    crossCuttingTags: [],
    constraints: {
      nightRotatingExposure: "possible",
      heavyPhysicalExposure: "low",
    },
    dimensionProfile: {
      workStyleFit: {
        independentTeam: lvl(5000),
        handsOnDesk: lvl(7500),
        structureJudgment: lvl(2500),
        routineVariety: lvl(5000),
        leadershipResponsibility: lvl(0),
      },
      physicalDemandTolerance: lvl(2500),
      indoorOutdoorPreference: lvl(0),
      customerFacingTolerance: lvl(2500),
      englishReadiness: lvl(5000),
      trainingDurationTolerance: lvl(5000),
      formalEntryWillingness: lvl(5000),
      shiftScheduleTolerance: lvl(5000),
      stabilityVersusUpside: lvl(5000),
      detailVersusCoordination: lvl(2500),
      careerEntryPracticality: "short-prep",
    },
    descriptionZh: "在临床实验室环境中支持标本处理与常规实验室辅助工作。",
    verification: { status: "editorial-only" },
    mismatchNotesZh:
      "偏实验室标本与化验支持，不同于诊所前台行政。",
    similarityGroupId: "sim-clinic-admin-vs-lab",
  },
] as const satisfies readonly CareerProfileV2[];
